# .goreleaser.yml
before:
  hooks:
  - go mod download

builds:
  -
    id: "restapi"
    dir: ./cve-alert-restapi
    main: ./main.go
    binary: cve-alert-restapi

  -
    id: "fetcher"
    dir: ./cve-alert-fetcher
    main: ./main.go
    binary: cve-alert-fetcher

archives:
  -
    builds:
    - restapi
    - fetcher
    
    replacements:
      amd64: 64-bit
      386: 32-bit
      darwin: macOS
