# official public key of CERT-BUND WID service (for verifying the received emails)
# see: https://www.cert-bund.de/wid-sig
certBundPublicKey: |
   -----BEGIN PGP PUBLIC KEY BLOCK-----
   Version: GnuPG v1.4.11 (GNU/Linux)

   mQINBFtDCIIBEADPmznoSE1Td6G1n5x2enpdai/gevKIOwpx+wDaKlupewVVcvhe
   Ki00TtATlH1M9bk2XY3waTd4IaTDUoYcY4p+MDfhlc81kKyEBJJLN8ApeTqeHs9N
   ZIhZcFI0bPSH+V3bxmbuoZi/Ac3ZsmTCankj7RV/ykpY+PmvhGRKiuCuJyRMvXUc
   IliOnAMVdRoeUW32TzQIvlmS6KXkQXHBa1wWm9GYoXfoF45YQhZobImaQXEaoEtz
   GUI92PnvB4ijIlfCHgr661ZdPSlctAFQDMBEXZuQz8s3SQ63P/HNth+QLpubGRNz
   KuyG6Cm6/mVQgIDxFRB7TqgH6afIDSOLTe4YUVtd8n8028VY7L8kw7TWcBH/6vNf
   /BM1mhX9HSkQ8ku4KSDVG46d2EH/ndKiXAcS9wPAxRFyvW+Fxt4ATDczwcqDR69k
   oEoUXnb4tbYr9uKyVDntAIhYYhsBR1gbBYEG9qNfekEmjyeHf8ekwGMZxlKo38IH
   y/eI5XOmiiJLGWnNus2pSG3E8wJ1UwaBySDPlOzsZocqdrV75vC40tSzQDOirxza
   Ree98w6ziyNY2hUoONjNxVZ3HXTIBQHEhLdBjntaMPutjmtsI8JLQXPYj5I48EB+
   ocaGZ0hBBqvC9kBllpwzNpQ+SxTg73FkLe0nn9lnZTsC0deMxA6h4001/wARAQAB
   tCVDRVJULUJ1bmQgV0lEIDx3aWRAbWFpbC5jZXJ0LWJ1bmQuZGU+iQI9BBMBAgAn
   AhsDBQkFo5qAAh4BAheABQJbQwkcBQsJCAcDBRUKCQgLBRYCAwEAAAoJEGRmZ6jJ
   75c2g7MP/jKWxb5ErYP+GXVy+jgw9H6PBv6psdi7HuxJ53dQg7iEQYCHRlxsWUan
   Ke3EZmef2F4gf0X34+nAFuk7ze6z+XmdzynQWNX9R56E2iriy+BYAK27f0vJOpMp
   chAGDN5fHMR+yKR/tjPiZ93K79XvpsOyZAVv+xb3kYOn0a+k2is2oMRcxwwuW+Vh
   JHmwH4lQJwgghDgWYMUuZNK+5+50fB7opBzEDe45bigOrD4SZmX1fKtVruQQ4Wx1
   JxXAclD9QFhstkRnEoLYNJJOHIdWXK6DFzep2BsG7AkQdDMsY7Tpss/qs+K0sgpT
   lN2FqXc80t/EWQI9b2TT0SRQmPsd+5gtZKOK0bkjLTgObRMo/kxhBAU5LOqYEboW
   ukUbE6j9WPhwR9T5y9MTEsgnSFs+06QpHFNsOMBqFobthvY9xLkSKJ/p6JkNF5Wa
   FpDZPmZH/2lJr9tIybv+A8okWZ7ew6MALXnQy6s/86CE5cbJuqvQeQ0s7D6rSkXg
   fQ4n+ufpJOCOwzreY+Q63nPsR5C2UWs+H9VTDzzh4VLYokHi9FDEvFC1UUnC9RCx
   +ORAvOn1HHs2cJgMBetf3ag3OpBOv9B+Ob6Z5pCbI5mZb73mqC4f3oxkI+gGWmMu
   1WdiOtiUNsrcgYlOcXGJPcwO6oMmGPLl9QMRQxLc2zqU4ccGah7BiQIcBBABCAAG
   BQJbQwnGAAoJEOMENImrC0oDbvIP/2fPYUN8S5Kw6sP9xT+IjPYWFXqNDui1JMh6
   W0FyW+qnY3A/O6Fjgh5fSjphm7p1T1hmSCT8I2ykuF6XGOMuiPR50C0gkAgX0b69
   ftcQW10GL5rGnAkQ6WOOGgo/jzayPZiq8ZFCti+VlhCBekBeoijH8Hr3GLBdceuU
   9Uycf72B6u3FlwoYSIPgECc+EvPi+Q93uc2I6qn2NqWggAV/gOUM1LWZGmmmognQ
   +1QEJ0qp19KxD8onXsFpA1zDdQLj2HQPVLF20lOMoaVhr/PZrmg6aQzAnzdwASB9
   yz1T/Fa4CYRz+awgbFAAGbVCpFNS7AILFvJTtlzG2GdLQEPXcBmD2xr5xOYrd9tR
   h6CGcQKs+5NNn7T8vA3ljVeRidoMz1evbyEWj+MAOo4FO5KAHkj+FSwseZELiBem
   OiW5DP3+vMRY9VF0L+/kfk7Y/kM1vh7MDS0GPvmXx/IexNuyMSyFeZq7bS3YnnFE
   0r15CVkCaqQVsFwbKFluT0zO9yTZieZIjbkAXUZxyr4JVPtqs0G2md5NwR1GgFiT
   0YuH1hbXvON1h1PN//7WF8mTvskySm69rNgUqS+sD1M5RS4aI5697Y0uN9ftGi2q
   BtSsQo0NWI1OGZVQi3tEUW3wlSnfzqH3w7W/Le4A20FqHg/ptkl7yIjsyPHxZEzB
   MCpi2EYC
   =5Vwu
   -----END PGP PUBLIC KEY BLOCK-----

# POP3 account credentials to received CERT-BUND WID emails
certBundPop3:
   # POP3 username
   Username: user
   # POP3 password
   Password: pass
   # POP3 hostname:port
   Host: localhost:110

# CVE database to store/read the CVE cases
cveDatabase:
   # database driver
   driverName: mysql
   # DSN
   dataSourceName: "user:password@/cve_alert_db"

#Default Port for REST API
restApi:
   port: 1323