filters: 1, Linux; 2, Windows; 3, Network; 4, Other
filter_categories: |
  1, Anwendung;
  2, Anwendung;
  3, Anwendung;
  3, Anwendung/Clients;
  1, Anwendung/Clients/Browser;
  2, Anwendung/Clients/Browser;
  3, Anwendung/Clients/Browser;
  1, Anwendung/Clients/Browser/Chrome;
  2, Anwendung/Clients/Browser/Chrome;
  3, Anwendung/Clients/Browser/Chrome;
  1, Anwendung/Clients/Browser/Firefox;
  2, Anwendung/Clients/Browser/Firefox;
  2, Anwendung/Clients/Browser/Internet_Explorer;
  1, Anwendung/Clients/Mail_Groupware/Thunderbird;
  2, Anwendung/Clients/Mail_Groupware/Thunderbird;
  1, Anwendung/Clients/Multimedia;
  2, Anwendung/Clients/Multimedia;
  2, Anwendung/Clients/Multimedia/Adobe_Flash_Player;
  2, Anwendung/Clients/Office;
  2, Anwendung/Clients/Office/Acrobat_Reader;
  1, Anwendung/Clients/Office/Foxit;
  2, Anwendung/Clients/Office/Foxit;
  2, Anwendung/Clients/Office/MS_Excel;
  2, Anwendung/Clients/Office/MS_Office;
  1, Anwendung/Clients/Office/OpenOffice;
  2, Anwendung/Clients/Office/OpenOffice;
  3, Anwendung/Security;
  3, Anwendung/Security/Antivirus;
  2, Anwendung/Security/Antivirus/Avira_Premium_Security_Suite;
  1, Anwendung/Security/Antivirus/ClamAV;
  2, Anwendung/Security/Antivirus/ClamAV;
  3, Anwendung/Security/Antivirus/ClamAV;
  2, Anwendung/Security/Antivirus/Kaspersky_Internet_Suite;
  1, Anwendung/Security/Antivirus/Symantec_Endpoint_Protection;
  2, Anwendung/Security/Antivirus/Symantec_Endpoint_Protection;
  1, Anwendung/Security/Crypto/OpenSSL;
  3, Anwendung/Security/IDS_Monitoring/wireshark;
  3, Anwendung/Server;
  3, Anwendung/Server/Backup_Storage/Tivoli_Storage_Manager;
  3, Anwendung/Server/Datenbanken;
  3, Anwendung/Server/Datenbanken/DB2;
  3, Anwendung/Server/Datenbanken/MS_SQL;
  3, Anwendung/Server/Datenbanken/MySQL;
  3, Anwendung/Server/Datenbanken/PostgreSQL;
  3, Anwendung/Server/Internet_Intranet_Infrastruktur;
  3, Anwendung/Server/Mail;
  3, Anwendung/Server/Mail/Microsoft_Exchange;
  3, Anwendung/Server/Sonstiges/JBoss;
  3, Anwendung/Server/Web_Content_Management;
  3, Anwendung/Server/Web_Content_Management/Drupal;
  3, Anwendung/Server/Web_Content_Management/JOOMLA;
  3, Anwendung/Server/Web_Proxy_Fileserver/Apache_Tomcat;
  3, Anwendung/Server/Web_Proxy_Fileserver/Squid;
  1, Anwendung/Virtualisierung_Emulation;
  2, Anwendung/Virtualisierung_Emulation;
  3, Anwendung/Virtualisierung_Emulation;
  2, Anwendung/Virtualisierung_Emulation/VMWare;
  3, Anwendung/Virtualisierung_Emulation/VMWare;
  1, Betriebssystem;
  2, Betriebssystem;
  1, Betriebssystem/Linux_Unix;
  1, Betriebssystem/Linux_Unix/AIX;
  1, Betriebssystem/Linux_Unix/Android;
  1, Betriebssystem/Linux_Unix/Debian;
  1, Betriebssystem/Linux_Unix/Fedora;
  1, Betriebssystem/Linux_Unix/FreeBSD;
  1, Betriebssystem/Linux_Unix/IOS;
  1, Betriebssystem/Linux_Unix/Mac_OS;
  1, Betriebssystem/Linux_Unix/RedHat;
  1, Betriebssystem/Linux_Unix/SuSE;
  1, Betriebssystem/Linux_Unix/Ubuntu;
  1, Betriebssystem/Oracle/OracleSystems;
  2, Betriebssystem/Oracle/OracleSystems;
  3, Betriebssystem/Windows/Windows_10;
  3, Betriebssystem/Windows/Windows_7;
  3, Betriebssystem/Windows/Windows_81;
  2, Betriebssystem/Windows/Windows_Server;
  3, Betriebssystem/Windows/Windows_Server;
  1, Hardware;
  2, Hardware;
  3, Hardware;
excluded_filter_categories: |